!$ const Alexanderpetree = 
new apetree100122 2FA,
( ${ auth: {{YOUR-TOKEN}},
    );await octokit.request
    ("GET 
    /repos/{apetree100122}
    /{*}
    /, 
    { owner: "apetree100122",
  repo: "*apetree100122*"});
on : 
workflow_dispatch:
jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repo content
  uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
    node-version: '16.17.0'
    cache: npm
      - name: Install dependencies
     run: npm install octokit
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
      - name: Run script
        run: |
          node .github/actions-scripts/use-the-api.mjs
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
